//
//  SpotifyGenres.swift
//  Newsic
//
//  Created by Miguel Alcantara on 19/10/2017.
//  Copyright © 2017 Miguel Alcantara. All rights reserved.
//

import Foundation

/*
 genreList:[String] = ["acoustic", "afrobeat", "alt-rock", "alternative", "ambient", "anime", "black-metal", "bluegrass", "blues", "bossanova", "brazil", "breakbeat", "british", "cantopop", "chicago-house", "children", "chill", "classical", "club", "comedy", "country", "dance", "dancehall", "death-metal", "deep-house", "detroit-techno", "disco", "disney", "drum-and-bass", "dub", "dubstep", "edm", "electro", "electronic", "emo", "folk", "forro", "french", "funk", "garage", "german", "gospel", "goth", "grindcore", "groove", "grunge", "guitar", "happy", "hard-rock", "hardcore", "hardstyle", "heavy-metal", "hip-hop", "holidays", "honky-tonk", "house", "idm", "indian", "indie", "indie-pop", "industrial", "iranian", "j-dance", "j-idol", "j-pop", "j-rock", "jazz", "k-pop", "kids", "latin", "latino", "malay", "mandopop", "metal", "metal-misc", "metalcore", "minimal-techno", "movies", "mpb", "new-age", "new-release", "opera", "pagode", "party", "philippines-opm", "piano", "pop", "pop-film", "post-dubstep", "power-pop", "progressive-house", "psych-rock", "punk", "punk-rock", "r-n-b", "rainy-day", "reggae", "reggaeton", "road-trip", "rock", "rock-n-roll", "rockabilly", "romance", "sad", "salsa", "samba", "sertanejo", "show-tunes", "singer-songwriter", "ska", "sleep", "songwriter", "soul", "soundtracks", "spanish", "study", "summer", "swedish", "synth-pop", "tango", "techno", "trance", "trip-hop", "turkish", "work-out", "world-music"]
 */
enum SpotifyGenres: String {
    case acoustic              = "Acoustic"
    case afrobeat              = "Afrobeat"
    case altRock              = "Alt-Rock"
    case alternative           = "Alternative"
    case ambient               = "Ambient"
    case anime                 = "Anime"
    case blackMetal           = "Black Metal"
    case bluegrass             = "Bluegrass"
    case blues                 = "Blues"
    case bossanova             = "Bossanova"
    case brazil                = "Brazil"
    case breakbeat             = "Breakbeat"
    case british               = "British"
    case cantopop              = "Cantopop"
    case chicagoHouse         = "Chicago-House"
    case children              = "Children"
    case chill                 = "Chill"
    case classical             = "Classical"
    case club                  = "Club"
    case comedy                = "Comedy"
    case country               = "Country"
    case dance                 = "Dance"
    case dancehall             = "Dancehall"
    case deathMetal           = "Death-Metal"
    case deepHouse            = "Deep-House"
    case detroitTechno        = "Detroit-Techno"
    case disco                 = "Disco"
    case disney                = "Disney"
    case drumAndBass         = "Drum-and-Bass"
    case dub                   = "Dub"
    case dubstep               = "Dubstep"
    case edm                   = "Edm"
    case electro               = "Electro"
    case electronic            = "Electronic"
    case emo                   = "Emo"
    case folk                  = "Folk"
    case forro                 = "Forro"
    case french                = "French"
    case funk                  = "Funk"
    case garage                = "Garage"
    case german                = "German"
    case gospel                = "Gospel"
    case goth                  = "Goth"
    case grindcore             = "Grindcore"
    case groove                = "Groove"
    case grunge                = "Grunge"
    case guitar                = "Guitar"
    case happy                 = "Happy"
    case hardRock             = "Hard-Rock"
    case hardcore              = "Hardcore"
    case hardstyle             = "Hardstyle"
    case heavyMetal           = "Heavy-Metal"
    case hipHop               = "Hip-Hop"
    case holidays              = "Holidays"
    case honkyTonk            = "Honky-Tonk"
    case house                 = "House"
    case idm                   = "Idm"
    case indian                = "Indian"
    case indie                 = "Indie"
    case indiePop             = "Indie-Pop"
    case industrial            = "Industrial"
    case iranian               = "Iranian"
    case jDance               = "J-Dance"
    case jIdol                = "J-Idol"
    case jPop                 = "J-Pop"
    case jRock                = "J-Rock"
    case jazz                  = "Jazz"
    case kPop                 = "K-Pop"
    case kids                  = "Kids"
    case latin                 = "Latin"
    case latino                = "Latino"
    case malay                 = "Malay"
    case mandopop              = "Mandopop"
    case metal                 = "Metal"
    case metalMisc            = "Metal-Misc"
    case metalcore             = "Metalcore"
    case minimalTechno        = "Minimal-Techno"
    case movies                = "Movies"
    case mpb                   = "Mpb"
    case newAge               = "New-Age"
    case newRelease           = "New-Release"
    case opera                 = "Opera"
    case pagode                = "Pagode"
    case party                 = "Party"
    case philippinesOpm       = "Philippines-Opm"
    case piano                 = "Piano"
    case pop                   = "Pop"
    case popFilm              = "Pop-Film"
    case postDubstep          = "Post-Dubstep"
    case powerPop             = "Power-Pop"
    case progressiveHouse     = "Progressive-House"
    case psychRock            = "Psych-Rock"
    case punk                  = "Punk"
    case punkRock             = "Punk-Rock"
    case rnb                 = "R-n-B"
    case rainyDay             = "Rainy-Day"
    case reggae                = "Reggae"
    case reggaeton             = "Reggaeton"
    case roadTrip             = "Road-Trip"
    case rock                  = "Rock"
    case rockNRoll           = "Rock-n-Roll"
    case rockabilly            = "Rockabilly"
    case romance               = "Romance"
    case sad                   = "Sad"
    case salsa                 = "Salsa"
    case samba                 = "Samba"
    case sertanejo             = "Sertanejo"
    case showTunes            = "Show-Tunes"
    case singerSongwriter     = "Singer-Songwriter"
    case ska                   = "Ska"
    case sleep                 = "Sleep"
    case songwriter            = "Songwriter"
    case soul                  = "Soul"
    case soundtracks           = "Soundtracks"
    case spanish               = "Spanish"
    case study                 = "Study"
    case summer                = "Summer"
    case swedish               = "Swedish"
    case synthPop             = "Synth-Pop"
    case tango                 = "Tango"
    case techno                = "Techno"
    case trance                = "Trance"
    case tripHop              = "Trip-Hop"
    case turkish               = "Turkish"
    case workOut              = "Work-Out"
    case worldMusic           = "World-Music"
    
    static let allValues = [acoustic, afrobeat, altRock, alternative, ambient, anime, blackMetal, bluegrass, blues, bossanova, brazil, breakbeat, british, cantopop, chicagoHouse, children, chill, classical, club, comedy, country, dance, dancehall, deathMetal, deepHouse, detroitTechno, disco, disney, drumAndBass, dub, dubstep, edm, electro, electronic, emo, folk, forro, french, funk, garage, german, gospel, goth, grindcore, groove, grunge, guitar, happy, hardRock, hardcore, hardstyle, heavyMetal, hipHop, holidays, honkyTonk, house, idm, indian, indie, indiePop, industrial, iranian, jDance, jIdol, jPop, jRock, jazz, kPop, kids, latin, latino, malay, mandopop, metal, metalMisc, metalcore, minimalTechno, movies, mpb, newAge, newRelease, opera, pagode, party, philippinesOpm, piano, pop, popFilm, postDubstep, powerPop, progressiveHouse, psychRock, punk, punkRock, rnb, rainyDay, reggae, reggaeton, roadTrip, rock, rockNRoll, rockabilly, romance, sad, salsa, samba, sertanejo, showTunes, singerSongwriter, ska, sleep, songwriter, soul, soundtracks, spanish, study, summer, swedish, synthPop, tango, techno, trance, tripHop, turkish, workOut, worldMusic]
    
    static let allShownValues = [acoustic, afrobeat, altRock, alternative, ambient, blackMetal, bluegrass, blues, bossanova, brazil, breakbeat, chicagoHouse, chill, classical, country, dance, dancehall, deathMetal, deepHouse, detroitTechno, disco, drumAndBass, dub, dubstep, edm, electro, electronic, emo, folk, forro, funk, gospel, goth, grindcore, groove, grunge, guitar, hardRock, hardcore, hardstyle, heavyMetal, hipHop, honkyTonk, house, idm, indie, indiePop, industrial, jDance, jIdol, jPop, jRock, jazz, kPop, latin, latino, mandopop, metal, metalMisc, metalcore, minimalTechno, newAge, opera, pagode, piano, pop, postDubstep, powerPop, progressiveHouse, psychRock, punk, punkRock, rnb, reggae, reggaeton, rock, rockNRoll, rockabilly, salsa, samba, sertanejo, ska, songwriter, soul, synthPop, tango, techno, trance, tripHop, worldMusic]
    
    
}
